import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Tanstackdevtool from "./Provider/tanstackdevtool";
import queryClient from "./Provider/Client";
import { Toaster } from "@/components/ui/toaster";
import Checkauthentification from "./(nav-included)/checkauthentification";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <span className="mb-100"></span>
        <TooltipProvider>
            {children}
        </TooltipProvider>
        <Toaster/>
      </body>
    </html>
  );
}
