import NavBar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Checkauthentification from "./checkauthentification";
import { Suspense, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense>
      <Checkauthentification >
        <NavBar />
        <span className="mb-100"></span>
        {children}
      </Checkauthentification>
    </Suspense>
  );
}
